### ISSUE TITLE
Test override CSS options for the homepage

### ISSUE THREAD

**Issue by alykat** [nprapps/elections16graphics#16]
- Can we hide the headline/teaser on a card?
- If so, can that be done w/ an override css file? Or inline CSS?

**Comment by JeromyCole** [comment]
You can use display:none when you want to hide these options.

Example:
#my-div p{
display:none;     //If inline styles exist in the element your changing, remove inline styles or use  
}                         // !important to override the styles that are in the tag itself. I would do the FIRST.       

This will remove any elements that are inside paragraph tags, which are also in the div "#my-div". You can use an included css file, I would recommend against inline css. 

*If the element has inline styles associated with it already, you will not be able to change the styles unless you use "!important". I don't recommend using !important (unless testing) because future coding becomes problematic.

**Comment by alykat** [comment]
Not going to need this.
