### ISSUE TITLE
Archive of election night data as it changes

### ISSUE THREAD

**Issue by lindamood** [nprapps/elections16graphics#71]
We need the ability to playback results over the course of the night for archive purposes and the creation of next day assets like an animation of the results map.

**Comment by TylerFisher** [comment]
Hm... I'm gonna need more information about this.

Saving the data over time is simple. Having something that replays all that data and recreates the map at a speed suitable for an animation is really quite hard.

**Comment by katiepark** [comment]
This doesn't help with the replaying of stored data, but here's the tool I mentioned to automate screenshotting of pages/graphics over the course of the night: https://github.com/washingtonpost/whippersnapper

We'd want to set up a machine that runs it (and respawns if it fails for some reason) and point it at the graphics we want to capture. But it could capture screenshots throughout the night for next-day use, rather than creating a replay rig to accomplish the same output.

**Comment by eads** [comment]
Let's use this ticket to track data archiving, and the one just referenced above to track screenshotting.

**Comment by TylerFisher** [comment]
Moving to general repo
